### ISSUE TITLE
Limit the zoom and panning area

### ISSUE THREAD

**Issue by tad-lispy** [johanhelsing/bevy_pancam#4]
Hi! Thanks for this useful plugin.

Is there a way to limit how much the camera can zoom in or out? Or how far it can pan away?

**Comment by johanhelsing** [comment]
Not currently, but it would probably be a useful feature to support.

Implementation-wise, we could just add two fields, `max_scale` and `min_scale` to the `PanCam` struct, and update the line here to use `clamp` instead of `max`: https://github.com/johanhelsing/bevy_pancam/blob/109d72e1a97ad28476ce0da9f26c488e15a83504/src/lib.rs#L36

Let me know if you want to have a got at it, or I might do it myself once I'm done with a couple of other projects.

Sorry for the slow response time.

**Comment by johanhelsing** [comment]
Since I implemented the zooming part of this, I created a new issue for the remaining panning/viewable area part. I wont be picking it up now, so feel free to have a go at it if you need the feature.
